/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CriarAvaliacaoDTO,
  VisualizarAvaliacao200,
  VisualizarAvaliacoes200
} from '../../model';




  export const getAvaliacaoController = (axiosInstance: AxiosInstance = axios) => {
const visualizarAvaliacao = (
    idPessoa: string,
    idEvento: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VisualizarAvaliacao200>> => {
    return axiosInstance.get(
      `/avaliacao/${idPessoa}/${idEvento}`,options
    );
  }
const avaliar = (
    idPessoa: string,
    idEvento: string,
    criarAvaliacaoDTO: CriarAvaliacaoDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/avaliacao/${idPessoa}/${idEvento}`,
      criarAvaliacaoDTO,{
    ...options,}
    );
  }
const visualizarAvaliacoes = (
    idInstituicao: string,
    idEvento: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VisualizarAvaliacoes200>> => {
    return axiosInstance.get(
      `/avaliacao/eventos/${idInstituicao}/${idEvento}`,options
    );
  }
return {visualizarAvaliacao,avaliar,visualizarAvaliacoes}};
export type VisualizarAvaliacaoResult = AxiosResponse<VisualizarAvaliacao200>
export type AvaliarResult = AxiosResponse<string>
export type VisualizarAvaliacoesResult = AxiosResponse<VisualizarAvaliacoes200>
