/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CadastroEventoDTO,
  ListarEvento200,
  ListarEventoParams,
  ViewRecompensaDTO
} from '../../model';




  export const getEventoController = (axiosInstance: AxiosInstance = axios) => {
const criarEvento = (
    cadastroEventoDTO: CadastroEventoDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/evento/criar`,
      cadastroEventoDTO,{
    ...options,}
    );
  }
const finalizarEvento = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.patch(
      `/evento/${id}/finalizar`,
      undefined,{
    ...options,}
    );
  }
const recompensasEvento = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ViewRecompensaDTO[]>> => {
    return axiosInstance.get(
      `/evento/recompensas/${id}`,options
    );
  }
const listarEvento = (
    params?: ListarEventoParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListarEvento200>> => {
    return axiosInstance.get(
      `/evento/listar`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {criarEvento,finalizarEvento,recompensasEvento,listarEvento}};
export type CriarEventoResult = AxiosResponse<string>
export type FinalizarEventoResult = AxiosResponse<string>
export type RecompensasEventoResult = AxiosResponse<ViewRecompensaDTO[]>
export type ListarEventoResult = AxiosResponse<ListarEvento200>
