/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CadastroEventoDTOTier = typeof CadastroEventoDTOTier[keyof typeof CadastroEventoDTOTier];


export const CadastroEventoDTOTier = {
  MOCK: 'MOCK',
} as const;
