/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CadastroDTO {
  /** @minLength 1 */
  nome: string;
  dataNascimento: string;
  /** @pattern ^\d{10,11}$ */
  telefone?: string;
  /** @minLength 1 */
  email: string;
  /**
     * @minLength 8
     * @maxLength 2147483647
     */
  senha: string;
  cpf?: string;
}
