/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CadastroEventoDTOSolicitacao = typeof CadastroEventoDTOSolicitacao[keyof typeof CadastroEventoDTOSolicitacao];


export const CadastroEventoDTOSolicitacao = {
  EM_ANALISE: 'EM_ANALISE',
  APROVADO: 'APROVADO',
  RECUSADO: 'RECUSADO',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  FINALIZADO: 'FINALIZADO',
} as const;
