/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CadastroEventoDTOAreaAtuacao } from './cadastroEventoDTOAreaAtuacao';
import type { CadastroEventoDTORecompensas } from './cadastroEventoDTORecompensas';
import type { CadastroEventoDTOSolicitacao } from './cadastroEventoDTOSolicitacao';
import type { CadastroEventoDTOTier } from './cadastroEventoDTOTier';

export interface CadastroEventoDTO {
  titulo?: string;
  dataHora?: string;
  localizacao?: string;
  idInstituicao?: string;
  lotacao?: number;
  descricao?: string;
  solicitacao?: CadastroEventoDTOSolicitacao;
  areaAtuacao?: CadastroEventoDTOAreaAtuacao;
  tier?: CadastroEventoDTOTier;
  fotos?: string[];
  recompensas?: CadastroEventoDTORecompensas;
  recompensasImagens?: { [key: string]: string };
}
