/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CriarAvaliacaoDTOTermosAvaliacaoItem = typeof CriarAvaliacaoDTOTermosAvaliacaoItem[keyof typeof CriarAvaliacaoDTOTermosAvaliacaoItem];


export const CriarAvaliacaoDTOTermosAvaliacaoItem = {
  BEM_ORGANIZADO: 'BEM_ORGANIZADO',
  MAL_ORGANIZADO: 'MAL_ORGANIZADO',
  PONTUAL: 'PONTUAL',
  ATRASADO: 'ATRASADO',
  BOA_COMUNICACAO: 'BOA_COMUNICACAO',
  IMPACTO_POSITIVO: 'IMPACTO_POSITIVO',
  ESTRUTURA_ADEQUADA: 'ESTRUTURA_ADEQUADA',
} as const;
