/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CriarAvaliacaoDTOTermosAvaliacaoItem } from './criarAvaliacaoDTOTermosAvaliacaoItem';

export interface CriarAvaliacaoDTO {
  termosAvaliacao?: CriarAvaliacaoDTOTermosAvaliacaoItem[];
  avaliacao?: number;
  comentario?: string;
}
