/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LoginDTO {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  senha: string;
}
