/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PessoaModelTier = typeof PessoaModelTier[keyof typeof PessoaModelTier];


export const PessoaModelTier = {
  NENHUM: 'NENHUM',
  BRONZE: 'BRONZE',
  PRATA: 'PRATA',
  OURO: 'OURO',
  DIAMANTE: 'DIAMANTE',
} as const;
