/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PessoaModelTier } from './pessoaModelTier';

export interface PessoaModel {
  /** @minLength 1 */
  nome: string;
  dataNascimento: string;
  /** @pattern ^\d{10,11}$ */
  telefone: string;
  /** @minLength 1 */
  email: string;
  tier?: PessoaModelTier;
  pontos?: number;
  eventosParticipados?: string[];
  id?: string;
  cpf?: string;
}
