/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecompensaPessoaDTOTierNecessario } from './recompensaPessoaDTOTierNecessario';

export interface RecompensaPessoaDTO {
  nomeInstituicao?: string;
  eventoNome?: string;
  recompensa?: string;
  tierNecessario?: RecompensaPessoaDTOTierNecessario;
  imagem?: string;
}
