/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ViewRecompensaDTOTierConta } from './viewRecompensaDTOTierConta';

export interface ViewRecompensaDTO {
  eventoNome?: string;
  eventoId?: string;
  recompensa?: string;
  tierConta?: ViewRecompensaDTOTierConta;
}
