/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecompensaPessoaDTO } from './recompensaPessoaDTO';
import type { ViewRecompensaPessoalDTOTierConta } from './viewRecompensaPessoalDTOTierConta';

export interface ViewRecompensaPessoalDTO {
  tierConta?: ViewRecompensaPessoalDTOTierConta;
  pontosProxT?: number;
  recompensas?: RecompensaPessoaDTO[];
}
