spring.application.name=Voluntier
spring.data.mongodb.username=${MONGO_USER}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.database=${MONGO_DB}
spring.data.mongodb.port=${MONGO_PORT}
spring.data.mongodb.host=localhost
spring.data.mongodb.authentication-database=admin
#Deixar falso esse aq (v) pq ele pode pesar caso o banco fique muito populoso
spring.data.mongodb.auto-index-creation=false
mongock.migration-scan-package=Vteam.Voluntier.db.migrations
