spring.application.name=Voluntier

spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USERNAME:admin}:${MONGO_ROOT_PASSWORD:admin}@localhost:27017/?authSource=admin
spring.data.mongodb.database=${MONGO_DATABASE:admin}

spring.data.mongodb.auto-index-creation=true
data.generation.enabled=true

jwt.secret=${JWT_SECRET:voluntier-dev-secret-key-minimo-32-caracteres}
jwt.expiration=28800000