/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CadastroDTO,
  LoginDTO,
  PessoaModel,
  ViewRecompensaPessoalDTO
} from '../../model';




  export const getPessoaController = (axiosInstance: AxiosInstance = axios) => {
const login = (
    loginDTO: LoginDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/user/Login`,
      loginDTO,{
    ...options,}
    );
  }
const cadastro = (
    cadastroDTO: CadastroDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/user/Cadastro`,
      cadastroDTO,{
    ...options,}
    );
  }
const testeAPI = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.get(
      `/user/teste`,{
    ...options,}
    );
  }
const recompensas = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ViewRecompensaPessoalDTO>> => {
    return axiosInstance.get(
      `/user/recompensas/${id}`,options
    );
  }
const ranking = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PessoaModel[]>> => {
    return axiosInstance.get(
      `/user/ranking`,options
    );
  }
return {login,cadastro,testeAPI,recompensas,ranking}};
export type LoginResult = AxiosResponse<string>
export type CadastroResult = AxiosResponse<string>
export type TesteAPIResult = AxiosResponse<string>
export type RecompensasResult = AxiosResponse<ViewRecompensaPessoalDTO>
export type RankingResult = AxiosResponse<PessoaModel[]>
