/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getInscricaoController = (axiosInstance: AxiosInstance = axios) => {
const inscrever = (
    idPessoa: string,
    idEvento: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/inscrever/${idPessoa}/${idEvento}`,
      undefined,{
    ...options,}
    );
  }
const cancelarInscricao = (
    idPessoa: string,
    idEvento: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.delete(
      `/inscrever/${idPessoa}/${idEvento}`,{
    ...options,}
    );
  }
return {inscrever,cancelarInscricao}};
export type InscreverResult = AxiosResponse<string>
export type CancelarInscricaoResult = AxiosResponse<string>
